---
# OpenShift Virtualization Migration Ansible Inventory

all:
  vars:
    # Baseline Variables
    aap_namespace: aap
    # aap_version: 2.5 # Defaults to 2.5 if not provided
    # aap_channel: stable-2.5 # Defaults to stable-2.5 if not provided
    aap_instance_name: 'aap'

    aap_execution_environment: OpenShift Virtualization Migration EE
    aap_project: OpenShift Virtualization Migration Project
    aap_org_name: OpenShift Virtualization Migration Org

    aap_validate_certs: false
    controller_validate_certs: false

    # If secure_logging is set to 'true', Secrets may be displayed in logs.
    # secure_logging: false

    ## Operators to deploy on the OpenShift Hub Cluster
    # aap_seed_operator_management_hub: []
    ## Operators to deploy on the OpenShift Spoke Clusters
    # aap_seed_operator_management_spoke: []

    # Automation Hub Variables
    automation_hub_certified_url: https://cloud.redhat.com/api/automation-hub/content/published/
    automation_hub_certified_auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

    automation_hub_validated_url: https://cloud.redhat.com/api/automation-hub/content/validated/
    automation_hub_validated_auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

# OpenShift Virtualization Migration Inventory Groups

# Migration Factory Hub cluster to configure
migration_hub:
  hosts:
    # Friendly name of the Hub
    hub.cluster.example.com:
      # OpenShift Variables for the Hub
      openshift_verify_ssl: false

      # Install AAP. Defaults to true. If false you must configure a host in the migration_factory_aap group.
      install_aap: false

# Migration Factory Hub spokes to configure
migration_spoke:
  hosts:
    # Friendly name of the Spoke
    spoke.cluster.example.com:
      # Host Variables
      openshift_verify_ssl: false

      # List of migration targets to configure on this specific spoke cluster
      configured_migration_targets:
        - vmware

      # Variables to apply to all configured job templates
      aap_job_template_extra_vars:

  ## Group Variables to apply to all spokes
  vars:
    migration_targets:
      - name: vmware
        type: vmware
        host: "{{ vmware_host }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        vddk:
          image: "{{ mtv_vmware_vddk_init_image }}"
          username: "{{ container_username }}"
          password: "{{ container_password }}"
        mapping:
          create: true
...